### ISSUE TITLE
Update Version?

### ISSUE THREAD

**Issue by georgiosdelimpasis** [cwi-vvatsos/home-assistant-olympia-electronics#1]
Any plans to update this? I really need this

**Comment by cwi-vvatsos** [comment]
I've updated it to work with the latest version of home assistant.
Copy the updated files into `/config/custom_components/olympia_electronics` and restart your HA
If it doesn't work, please add to your config
```
logger:
  default: warning
    logs:
      custom_components.olympia_electronics.climate: debug
```
and monitor your logs for errors and post them here.
Let me know if it works for you
